### ISSUE TITLE
Possible to add Event with var?

### ISSUE THREAD

**Issue by silverowiec** [Grible/timetable.js#10]
I want to add events dynamically so I need to put a var e.g. var event = "Birthday" into addEvent() but  timetable does not add it. How can I do this?

**Comment by GinoNL** [comment]
Hi @silverowiec , I'm not sure I fully understand, could you elaborate please?

**Comment by silverowiec** [comment]
Oh I'm sorry I solved the problem which wasn't caused by TimeTable.js. Please close this topic. Best regards
