### ISSUE TITLE
[Styling Enhancement] Optional Horizontal Scroll fallback

### ISSUE THREAD

**Issue by CptMeatball** [Grible/timetable.js#18]
The current CSS sets `overflow-x: scroll`. While this isn't a problem for light themed websites, it's an inconvenience for dark themed timetables. The scrollbar stands out in a not so positive way ;)
![screen shot 2016-10-11 at 15 38 10](https://cloud.githubusercontent.com/assets/1681727/19272414/c133192a-8fc8-11e6-9764-cd77bef34472.png)

I tried JScrollPane but this breaks the functionality of TimetableJS. Anyone got a working library or fix for this?
I tagged this as an optional enhancement, as it would be great if this functionality can be supplemented without the need of external sources that might break functionality.

**Comment by stevenaanen** [comment]
I think this is browser default behavior and depends on the combination of browser and OS used. Not sure if there are (not hacky) enhancements possible to Timetable.js to fix this. You might want to consider adding a few css hacks to hide the scroll bars in your own website if that's the desired result. They are easy to find on Google :).
