### ISSUE TITLE
It need a ui to create event

### ISSUE THREAD

**Issue by pfloriginale** [Grible/timetable.js#21]
Hi steven,
you done a great job... 

I'm developping an ERP for restaurant and I would like to use this for schedule timetable worker, but, i need a user interface to schedule.

E.g.
1 - Restaurant manager open my erp
2 - He see the list of the employer of the restaurant;
3 - Choose the employe from the list and make the timetable;
4 - Employ can see the time table of the week;

Could you suggest me a way?

May I help you?

**Comment by stevenaanen** [comment]
Hi @pfloriginale! At this moment timetable.js can be used for displaying timetables only, not editing them. You could of course write some application logic around it and use timetable.js just for display purposes (refresh the view every time you make a change to the schedule using the API).
