### ISSUE TITLE
how can catch click empty area event??

### ISSUE THREAD

**Issue by techinpark** [Grible/timetable.js#28]
i wanna know when i click empty area catch event (get clicked area time) 
how can i do ?

**Comment by stevenaanen** [comment]
It took a while, but I'm adding an option for this as we speak. You'll be able to attach a function to each event, which will be called whenever the event is clicked. It will also pass on the event so you can use it's metadata, as well as the timetable it is in (so it can be adapted based on the click for instance). I'll try to build a new release today.
