### ISSUE TITLE
Is it possible for multiple events to resize if they share the same time ?

### ISSUE THREAD

**Issue by powerfulsheron** [Grible/timetable.js#29]
Idk if my question is clear, but i would like to know if it could be possible to have resizing events who share same time like in the dhtmlx scheduler :
https://dhtmlx.com/docs/products/dhtmlxScheduler/sample_basic.shtml

See the image below :

<img width="173" alt="2017-07-13_15h45_08" src="https://user-images.githubusercontent.com/18470816/28169332-4426bcf0-67e2-11e7-8517-5009a36af9cc.png">

**Comment by hazzed** [comment]
How did you switch the times to the side and titles to top? I'm looking to do that

**Comment by powerfulsheron** [comment]
I did not switch anything this is a picture of another js scheduler

**Comment by stevenaanen** [comment]
Unfortunately this is not possible currently. Timetable.js is not really for calendar-like applications, but for displaying timetables. For instance for listing events over time per location/room. There's currently no plan to add calender-like functionality.
