### ISSUE TITLE
Question: Does this support portrait mode?

### ISSUE THREAD

**Issue by SquireOfSoftware** [Grible/timetable.js#32]
I have noticed the demo only does landscape and there doesn't appear to be a lot of documentation as to what the different options are (without looking further into the source code).
I am going to assume that this doesn't exist as of yet...right?

**Comment by stevenaanen** [comment]
That's right. There are not many options yet, just the ones listed in the README. What is your question exactly?

**Comment by SquireOfSoftware** [comment]
Whether or not the timetable can go into portrait view. But it is okay, I found another github repository which supplies what I am after. Sorry about the question.
