### ISSUE TITLE
Request: custom class/data attributes on events

### ISSUE THREAD

**Issue by djgadd** [Grible/timetable.js#4]
It would be nice if, instead of a URL as the last parameter, the method accepted an object where we could add additional additional attributes that get added to the event, eg:

```
{
  url: 'https://google.com',
  class: 'google another-class private',
  data: {
    id: 1,
    private: true,
    organiser: 'Daniel'
  }
}
```

I may be able to put a PR together this weekend if it's an enhancement you'd be interested in?

**Comment by stevenaanen** [comment]
Hi @djgadd! Sounds like a great addition. I think it's something that would benefit multiple devs.

How would you suggest to make the data-object accessible? Using HTML-attributes or just in the Javascript API perhaps?

**Comment by djgadd** [comment]
@stevenaanen I was thinking just data attributes on the individual events to keep it simple, but if someone has a use case for an API to access events through the Timetable object I'm happy to take suggestions.

My current use case is that I need to attach arbitrary data/context to the events so that I can perform additional tasks when an event is clicked.

**Comment by stevenaanen** [comment]
I see! Maybe it would be an idea to make the data accessible using the API to attach custom behaviour like in your use case, and make it up to the dev in some way to attach data attributes to the HTML as well? I’m a bit afraid that it might clutter up the HTML too much if all data fields are attached to the HTML by default.

We could for instance solve this by attaching callback handlers to click/hover events. A dev can then register a callback function, and when an event fires, it would give the event object including custom data to the handler.

I’m not sure what you think about this. Would it be helpful in your case?

**Comment by djgadd** [comment]
Is HTML clutter a problem? I can't imagine very many end users are going to be offended if they open the  page source and see lots of data attributes on elements. I think (in this case) it would be simpler to use the data attributes as they were intended, and let the dev shoulder the accountability of using data attributes responsibly.

If we're to build an API then I think we'd need an Event object that was returned by the addEvent method, we'd probably need to implement listeners that trigger when the Event object changes on top of exposing click/tap/hover events. If we use the data attributes we mitigate a lot of that "responsibility" and allow the dev to handle it using whatever means they see fit, keeping the library vanilla.

Exposing an API may well be something worth doing down the line, but I think it would require a major version change as it would change already existing methods, return types and data structures.

What do you think?

**Comment by djgadd** [comment]
Tweaked the idea a bit, the last parameter of the addEvent method can be an optional object of attributes that will be added (rather than being hardcoded to accept only certain object keys.)

It might be worth looking at building out an API as this library grows, but I think for the sake of simplicity (which this library does very well) the above will suffice.

**Comment by stevenaanen** [comment]
I guess you're right regarding the API, that might be smart to add in a later phase. For the moment it would be ok to use data attributes.

Thanks for the PR! I'll try to set free some time after the weekend to have a better look at it if that's ok with you. Currently a bit busy with other things. Happy that you directly picked this up though!

**Comment by djgadd** [comment]
No problem, give me a shout if there’s anything you want me to take another look at, thanks for providing the library!

**Comment by betz** [comment]
@djgadd could you do a gulp build and include this in your release?
I am unable to build the minified version. I am getting a lot of jslint errors, and in the end, a uglify-js error.

The readme on your fork refers already to this new data attributes, but the minified version doesn't include this.
