### ISSUE TITLE
12-Hour time?

### ISSUE THREAD

**Issue by Ghosts** [Grible/timetable.js#46]
Hi, I looked through the issues and didn't find a reference to using 12-hour instead of 24-hour time, and the docs didn't appear to have settings for that. I was wondering if this is possible / if there are plans to enable switching time formats? 

Thank you!

**Comment by stevenaanen** [comment]
Hi! There's no native feature for 12-hour time at this moment. Would be happy to merge in contributions for this though.

If your events all fit into just AM or just PM, you could reach this behavior by using 1 to 13 hours as scope, and converting your time entries to fit into those 12 hours.
