### ISSUE TITLE
Custom color for events

### ISSUE THREAD

**Issue by chmlife** [Grible/timetable.js#6]
Is there any way to assign colors to different events?

**Comment by stevenaanen** [comment]
@chmlife you can style based on order/attribute/etc with custom css of course. But if you need to do this via the javascript API there's currently no way to do that. 

How are you planning to use timetable with colors? Just curious. Maybe it would be useful for more people to add some functionality for that.

**Comment by chmlife** [comment]
Thank you for you reply ;)
My purpose is to assign a color to certain events.
e.g. red to event A, green to event B.
So the users can see the difference and proportion to certain kind of events.

However, I made it by changing the plugin.js as
addEvent: function(name, location, start, end, url, custom_class) {
...
			this.events.push({
				name: name,
				location: location,
				startDate: start,
				endDate: end,
				url: url,
				custom_class: custom_class
			});
...
			function appendEvent(event, node) {
				...
				//aNode.className = 'time-entry';
				aNode.className = node["custom_class"];
                               ...


and overwriting timetable.css with:
.timetable .custom-red{
    background-color: #E95547;
    transition: 200ms background-color;
    height: 45px;
    display: block;
    position: absolute;
    z-index: 2;
    padding: 0 10px;
    white-space: normal;
    overflow: hidden;
    color: #fff;
    border: 1px solid #e32c1b;
    -webkit-transform-style: preserve-3d;
    transform-style: preserve-3d
}
...

So I could call the addEvent method with one more parameter.
timetable.addEvent(name,loc, start, end, '#','time-entry custom-red');
Then, it assign both of the classes to the event.
I am not very familiar with the javascript, but it partially fulfill my requirements.

**Comment by stevenaanen** [comment]
Great suggestion! I'll try to have a look at it in the coming weeks (we're a bit busy now). We might be able to combine this with request #4 in some way

**Comment by TheAksh** [comment]
So, can custom colors be set for each event via the API now? If yes, can someone please specify the procedure clearly?
